rollout:
  tasks:
    - task_name: calvin_move_slider_left
      instruction: move the slider left
      params:
        subtask: move_slider_left
        initial_state:
          led: 0
          lightbulb: 0
          slider: right
          drawer: closed
          red_block: table
          blue_block: slider_right
          pink_block: slider_left
          grasped: 0
