cluster:
  gpus:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  policy_gpus:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
  openpi_gpus:
    - 6
  robotwin_gpus:
    - 7
  ray_num_workers: 4

openrlhf:
  tensor_parallel_size: 2
  max_model_len: 32768
  max_num_batched_tokens: 32768
  gpu_memory_utilization: 0.7
